AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CreateVector-app

  Sample SAM Template for CreateVector-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RegistVectorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: registVector/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          EXTERNAL_MODULES: "@tensorflow/tfjs-node"
      Architectures:
        - x86_64
      Events:
        RegistVector:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /registVector
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RegistVectorApi:
    Description: "API Gateway endpoint URL for Prod stage for Reegister Vector function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/registVector/"
  RegistVectorFunction:
    Description: "Register Vector Lambda Function ARN"
    Value: !GetAtt RegistVectorFunction.Arn
  RegistVectorFunctionIamRole:
    Description: "Implicit IAM Role created for Register Vector function"
    Value: !GetAtt RegistVectorFunctionRole.Arn
